Controllers/CorreioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BellinatiCorreio.Views.Home;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SicWEB.Data;
using SicWEB.Models;

namespace SicWEB.Controllers {
  [Authorize]
  public class CorreioController : Controller {
    static Conexao c = new Conexao();
    public static string sql = c.ConexaoDados();
    private readonly ApplicationDbContext _context;

    public CorreioController(ApplicationDbContext context) {
      _context = context;
    }

    // GET: Correio
    [Authorize(Policy = "usuario")]
    public async Task<IActionResult> Index() {
      ViewBag.NomeUser = c.NomeUser(User.Identity.Name);
      return View(await _context.Correio.ToListAsync());
    }

    // GET: Correio/Details/5
    [Authorize(Policy = "usuario")]
    public async Task<IActionResult> Details(int? id) {
      if (id == null) {
        return NotFound();
      }

      var correio = await _context.Correio
          .FirstOrDefaultAsync(m => m.Id == id);
      if (correio == null) {
        return NotFound();
      }
      ViewBag.NomeUser = c.NomeUser(User.Identity.Name);
      return View(correio);
    }

    // GET: Correio/Create
    public IActionResult Create() {
      ViewBag.NomeUser = c.NomeUser(User.Identity.Name);
      ViewBag.SetorUser = c.SetorUser(User.Identity.Name);
      return View();
    }

    // POST: Correio/Create
    // To protect from overposting attacks, enable the specific properties you want to bind to.
    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [Authorize(Policy = "usuario")]
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create([Bind("Id,Status,DataEnvio,Tipo,Destinatario,Cidade,Remetente,Setor,Atualizacao")] Correio correio) {
      if (ModelState.IsValid) {
        _context.Add(correio);
        await _context.SaveChangesAsync();
        ViewBag.NomeUser = c.NomeUser(User.Identity.Name);
        TempData["mensagemCreate"] = "MSG";
        return RedirectToAction(nameof(Index));
      }
      ViewBag.NomeUser = c.NomeUser(User.Identity.Name);
      return View(correio);
    }

    // GET: Correio/Edit/5
    [Authorize(Policy = "admin")]
    public async Task<IActionResult> Edit(int? id) {
      if (id == null) {
        return NotFound();
      }

      var correio = await _context.Correio.FindAsync(id);
      if (correio == null) {
        return NotFound();
      }
      ViewBag.NomeUser = c.NomeUser(User.Identity.Name);
      return View(correio);
    }

    // POST: Correio/Edit/5
    // To protect from overposting attacks, enable the specific properties you want to bind to.
    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [Authorize(Policy = "admin")]
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, [Bind("Id,Status,DataEnvio,Tipo,Destinatario,Cidade,Remetente,Setor,Atualizacao")] Correio correio) {
      if (id != correio.Id) {
        return NotFound();
      }

      if (ModelState.IsValid) {
        try {
          _context.Update(correio);
          await _context.SaveChangesAsync();
        }
        catch (DbUpdateConcurrencyException) {
          if (!CorreioExists(correio.Id)) {
            return NotFound();
          } else {
            throw;
          }
        }
        ViewBag.NomeUser = c.NomeUser(User.Identity.Name);
        TempData["mensagemEdit"] = "MSG";
        return RedirectToAction(nameof(Index));
      }

      ViewBag.NomeUser = c.NomeUser(User.Identity.Name);
      return View(correio);
    }

    // GET: Correio/Delete/5
    [Authorize(Policy = "super")]
    public async Task<IActionResult> Delete(int? id) {
      if (id == null) {
        return NotFound();
      }

      var correio = await _context.Correio
          .FirstOrDefaultAsync(m => m.Id == id);
      if (correio == null) {
        return NotFound();
      }

      ViewBag.NomeUser = c.NomeUser(User.Identity.Name);
      return View(correio);
    }

    // POST: Correio/Delete/5
    [Authorize(Policy = "super")]
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(int id) {
      var correio = await _context.Correio.FindAsync(id);
      _context.Correio.Remove(correio);
      await _context.SaveChangesAsync();
      ViewBag.NomeUser = c.NomeUser(User.Identity.Name);
      TempData["mensagemDelete"] = "MSG";
      return RedirectToAction(nameof(Index));
    }

    private bool CorreioExists(int id) {
      return _context.Correio.Any(e => e.Id == id);
    }
  }
}

Controllers/MalotesController.cs
using BellinatiCorreio.Views.Home;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MySqlConnector;
using PdfSharpCore.Drawing;
using SicWEB.Data;
using SicWEB.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace SicWEB.Controllers {
  [Authorize]
  public class MalotesController : Controller {
    static Conexao c = new Conexao();
    static Mail mail = new Mail();

    public static string sql = c.ConexaoDados();

    private readonly ApplicationDbContext _context;

    public MalotesController(ApplicationDbContext context) {
      _context = context;
    }

    // GET: Malotes
    public async Task<IActionResult> Index() {
      ViewBag.NomeUser = c.NomeUser(User.Identity.Name);
      return View(await _context.Malote.ToListAsync());
    }

    // GET: Malotes/Details/5
    public async Task<IActionResult> Details(int? id) {
      if (id == null) {
        return NotFound();
      }

      var malote = await _context.Malote
          .FirstOrDefaultAsync(m => m.Id == id);
      if (malote == null) {
        return NotFound();
      }

      ViewBag.NomeUser = c.NomeUser(User.Identity.Name);
      return View(malote);
    }


    // GET: Malotes/Create
    [Authorize(Policy = "usuario")]
    public IActionResult Create() {
      ViewBag.CidadeUser = c.CidadeUser(User.Identity.Name);
      ViewBag.NomeUser = c.NomeUser(User.Identity.Name);
      return View();
    }

    // POST: Malotes/Create
    // To protect from overposting attacks, enable the specific properties you want to bind to.
    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    [Authorize(Policy = "usuario")]
    public async Task<IActionResult> Create([Bind("Id,Numero,Percurso,Lacre,Cidade,Remetente,Status,Atualizacao,DataEnvio,DataRecebido,CidadeSaida,NomeUser")] Malote malote) {
      if (ModelState.IsValid) {
        _context.Add(malote);
        await _context.SaveChangesAsync();
        TempData["mensagemCreate"] = "MSG";
        var remetente = c.EmailUser(User.Identity.Name);
        mail.enviaMalote(malote.Status, malote.DataEnvio, malote.Cidade, malote.Numero, malote.Percurso, malote.Lacre, malote.Remetente, remetente);
        return RedirectToAction(nameof(Index));
      }

      ViewBag.NomeUser = c.NomeUser(User.Identity.Name);
      return View(malote);
    }

    // GET: Malotes/Edit/5
    [Authorize(Policy = "admin")]
    public async Task<IActionResult> Edit(int? id) {
      if (id == null) {
        return NotFound();
      }

      var malote = await _context.Malote.FindAsync(id);
      if (malote == null) {
        return NotFound();
      }
      ViewBag.NomeUser = c.NomeUser(User.Identity.Name);
      return View(malote);
    }

    // POST: Malotes/Edit/5
    // To protect from overposting attacks, enable the specific properties you want to bind to.
    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [Authorize(Policy = "admin")]
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, [Bind("Id,Numero,Percurso,Lacre,Cidade,Remetente,Status,Atualizacao,DataEnvio,DataRecebido,CidadeSaida,NomeUser")] Malote malote) {
      if (id != malote.Id) {
        return NotFound();
      }

      if (ModelState.IsValid) {
        try {
          _context.Update(malote);
          await _context.SaveChangesAsync();
        }
        catch (DbUpdateConcurrencyException) {
          if (!MaloteExists(malote.Id)) {
            return NotFound();
          } else {
            throw;
          }
        }
        var remetente = c.EmailUser(User.Identity.Name);
        mail.atualizaMalote(malote.Status, malote.DataEnvio, malote.Cidade, malote.Numero, malote.Percurso, malote.Lacre, malote.Remetente, remetente);
        TempData["mensagemEdit"] = "MSG";
        return RedirectToAction(nameof(Index));
      }
      ViewBag.NomeUser = c.NomeUser(User.Identity.Name);
      return View(malote);
    }

    // GET: Malotes/Delete/5
    [Authorize(Policy = "super")]
    public async Task<IActionResult> Delete(int? id) {
      if (id == null) {
        return NotFound();
      }

      var malote = await _context.Malote
          .FirstOrDefaultAsync(m => m.Id == id);
      if (malote == null) {
        return NotFound();
      }
      ViewBag.NomeUser = c.NomeUser(User.Identity.Name);
      return View(malote);
    }

    // POST: Malotes/Delete/5
    [Authorize(Policy = "super")]
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(int id) {
      var malote = await _context.Malote.FindAsync(id);
      _context.Malote.Remove(malote);
      await _context.SaveChangesAsync();
      TempData["mensagemDelete"] = "MSG";
      return RedirectToAction(nameof(Index));
    }

    private bool MaloteExists(int id) {
      return _context.Malote.Any(e => e.Id == id);
    }

    public FileResult GerarRelatorio() {
      using (var doc = new PdfSharpCore.Pdf.PdfDocument()) {
        var page = doc.AddPage();
        page.Size = PdfSharpCore.PageSize.A4;
        page.Orientation = PdfSharpCore.PageOrientation.Portrait;

        List<Malote> lst = new List<Malote>();
        lst.Add(new Malote() { Remetente = "Teste", Cidade = "Teste" });

        var grafics = PdfSharpCore.Drawing.XGraphics.FromPdfPage(page);
        var corFonte = PdfSharpCore.Drawing.XBrushes.Black;
        var textFormatter = new PdfSharpCore.Drawing.Layout.XTextFormatter(grafics);
        var fonteOrganizacao = new PdfSharpCore.Drawing.XFont("Arial", 10);
        var fonteTitulo = new PdfSharpCore.Drawing.XFont("Arial", 10, PdfSharpCore.Drawing.XFontStyle.Bold);
        var fonteDesc = new PdfSharpCore.Drawing.XFont("Arial", 8, PdfSharpCore.Drawing.XFontStyle.Bold);
        var titulo = new PdfSharpCore.Drawing.XFont("Arial", 14, PdfSharpCore.Drawing.XFontStyle.Bold);
        var fonteDetalhes = new PdfSharpCore.Drawing.XFont("Arial", 7);
        var logo = @"C:\Logo.png";

        var qtdpaginas = doc.PageCount;

        textFormatter.DrawString(qtdpaginas.ToString(), new PdfSharpCore.Drawing.XFont("Arial", 7), corFonte,
          new PdfSharpCore.Drawing.XRect(575, 825, page.Width, page.Height));

        XImage imagem = XImage.FromFile(logo);
        grafics.DrawImage(imagem, 160, 15, 280, 150);

        textFormatter.DrawString("Protocolo de Envio de Malote", titulo, corFonte, new PdfSharpCore.Drawing.XRect(200, 160, page.Width, page.Height));

        textFormatter.DrawString("REMETENTE", fonteTitulo, corFonte, new PdfSharpCore.Drawing.XRect(70, 210, page.Width, page.Height));
        textFormatter.DrawString("DESTINO", fonteTitulo, corFonte, new PdfSharpCore.Drawing.XRect(170, 210, page.Width, page.Height));
        textFormatter.DrawString("N. LACRE ", fonteTitulo, corFonte, new PdfSharpCore.Drawing.XRect(270, 210, page.Width, page.Height));
        textFormatter.DrawString("PERCURSO", fonteTitulo, corFonte, new PdfSharpCore.Drawing.XRect(370, 210, page.Width, page.Height));
        textFormatter.DrawString("N. MALOTE", fonteTitulo, corFonte, new PdfSharpCore.Drawing.XRect(470, 210, page.Width, page.Height));


        List<Malote> alunos = new List<Malote>();

        MySqlConnection con = new MySqlConnection();
        con.ConnectionString = c.ConexaoDados();
        con.Open();
        string data = DateTime.Now.ToShortDateString();
        //Npgsql.NpgsqlCommand command = new Npgsql.NpgsqlCommand("SELECT" + '"' + "Remetente" + '"' + " , " + '"' + "Cidade" + "FROM" + '"' + "MaloteModel" + '"', con);
        MySqlCommand command = new MySqlCommand("SELECT * FROM Malote  WHERE  DataEnvio = '" + DateTime.Today.ToString("yyyy/MM/dd") + "'", con);
        MySqlDataReader reader = command.ExecuteReader();
        if (reader.HasRows) {
          while (reader.Read()) {
            alunos.Add(new Malote() {
              CidadeSaida = reader.GetString("CidadeSaida"),
              Cidade = reader.GetString("Cidade"),
              Lacre = reader.GetInt32("Lacre"),
              Percurso = reader.GetInt32("Percurso"),
              Numero = reader.GetInt32("Numero")

            });
          }
          Console.WriteLine(data);
        }

        var alturaItens = 230;
        for (int i = 0; i < alunos.Count; i++) {
          textFormatter.DrawString(alunos[i].CidadeSaida, fonteOrganizacao, corFonte, new PdfSharpCore.Drawing.XRect(70, alturaItens, page.Width, page.Height));
          textFormatter.DrawString(alunos[i].Cidade, fonteOrganizacao, corFonte, new PdfSharpCore.Drawing.XRect(170, alturaItens, page.Width, page.Height));
          textFormatter.DrawString(alunos[i].Lacre.ToString(), fonteOrganizacao, corFonte, new PdfSharpCore.Drawing.XRect(270, alturaItens, page.Width, page.Height));
          textFormatter.DrawString(alunos[i].Percurso.ToString(), fonteOrganizacao, corFonte, new PdfSharpCore.Drawing.XRect(370, alturaItens, page.Width, page.Height));
          textFormatter.DrawString(alunos[i].Numero.ToString(), fonteOrganizacao, corFonte, new PdfSharpCore.Drawing.XRect(470, alturaItens, page.Width, page.Height));

          alturaItens += 20;
        }

        textFormatter.DrawString("________________________________", fonteOrganizacao, corFonte,
          new PdfSharpCore.Drawing.XRect(50, 750, page.Width, page.Height));

        textFormatter.DrawString("________________________________", fonteOrganizacao, corFonte,
          new PdfSharpCore.Drawing.XRect(360, 750, page.Width, page.Height));

        textFormatter.DrawString("Correios", fonteOrganizacao, corFonte,
          new PdfSharpCore.Drawing.XRect(50, 770, page.Width, page.Height));

        textFormatter.DrawString("Grupo Bellinati", fonteOrganizacao, corFonte,
          new PdfSharpCore.Drawing.XRect(360, 770, page.Width, page.Height));

Controllers/RoleController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;

namespace SIC.Controllers {
  public class RoleController : Controller {
    RoleManager<IdentityRole> roleManager;

    public RoleController(RoleManager<IdentityRole> roleManager) {
      this.roleManager = roleManager;
    }

    [Authorize(Policy = "super")]
    public IActionResult Index() {
      var roles = roleManager.Roles.ToList();
      return View(roles);
    }

    [Authorize(Policy = "super")]
    public IActionResult Create() {
      return View(new IdentityRole());
    }

    [HttpPost]
    public async Task<IActionResult> Create(IdentityRole role) {
      await roleManager.CreateAsync(role);
      return RedirectToAction("Index");
    }
  }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>@ViewData["Title"] - SicWEB</title>
  <!-- MDB icon -->
  <link rel="icon" href="~/img/favicon.ico" type="image/x-icon">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="~/css/bootstrap.min.css">
  <!-- Material Design Bootstrap -->
  <link rel="stylesheet" href="~/css/mdb.min.css">
  <!-- Your custom styles (optional) -->
  <link rel="stylesheet" href="~/css/style.css">
  <!-- Stepper CSS - minified-->
  <link href="~/css/addons-pro/steppers.min.css" rel="stylesheet">
  <!-- DataTables CSS - minified-->
  <link href="https://cdn.datatables.net/1.10.24/css/dataTables.bootstrap4.min.css" rel="stylesheet">
  <!-- MDBootstrap Cards Extended Pro  -->
  <link href="~/css/addons-pro/cards-extended.min.css" rel="stylesheet">
  <!-- MDBootstrap flags -->
  <link href="~/css/addons/flag.min.css" rel="stylesheet">

</head>
<body>
  <header>
    @if (SignInManager.IsSignedIn(User)) {
      <!--Navbar -->
      <nav class="mb-1 navbar navbar-expand-lg navbar-dark bg-danger-dark">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
          <img src="~/img/topo.png" style="width: 40px" class="d-inline-block align-top" alt="">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent-333"
                aria-controls="navbarSupportedContent-333" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent-333">
          <ul class="navbar-nav mr-auto">

            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle text-white hvr-underline-reveal" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-truck"></i> Correios
              </a>
              <div class="dropdown-menu dropdown-dark" aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item" asp-area="" asp-controller="Correio" asp-action="Index">
                  <i class="fas fa-plus-circle"></i>&nbsp; Cadastro de Encomendas
                </a>
                <a class="dropdown-item" asp-area="" asp-controller="Malotes" asp-action="Index">
                  <i class="fas fa-plus-circle"></i>&nbsp; Cadastro de Malotes
                </a>
              </div>
            </li>

            <!--
            <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle text-white hvr-underline-reveal" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-highlighter"></i> Materiais
            </a>
            <div class="dropdown-menu dropdown-dark " aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item">
            <i class="fas fa-plus-circle"></i>&nbsp; Solicitação de Materiais
            </a>
            <a class="dropdown-item">
            <i class="fas fa-list-ul"></i> Listagens de Solicitações
            </a>
            </div>
            </li>

            <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle text-white hvr-underline-reveal" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-external-link-square-alt"></i> Externos
            </a>
            <div class="dropdown-menu dropdown-dark" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item">
            <i class="fas fa-external-link-alt"></i> Rastreio Azul
            </a>
            <a class="dropdown-item">
            <i class="fas fa-external-link-alt"></i> Rastreio Correios
            </a>
            </div>
            </li>

            <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle text-white hvr-underline-reveal" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-chart-line"></i> Gráficos
            </a>
            <div class="dropdown-menu dropdown-dark" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item">
            <i class="far fa-chart-bar"></i> Gráfico de Correios
            </a>
            <a class="dropdown-item">
            <i class="far fa-chart-bar"></i> Gráfico de Malotes
            </a>
            <a class="dropdown-item">
            <i class="far fa-chart-bar"></i> Gráfico de Materiais
            </a>
            </div>
            </li>
            -->

            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle text-white hvr-underline-reveal" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-file-signature"></i> Notificações
              </a>
              <div class="dropdown-menu dropdown-dark" aria-labelledby="navbarDropdownMenuLink" id="notificacao">
                <input class="form-control" type="text" placeholder="Buscar" aria-label="Search">
                <a class="dropdown-item" asp-area="" asp-controller="CitacaoCarta" asp-action="Index">
                  <i class="fas fa-copy"></i> Citação por Carta
                </a>
                <a class="dropdown-item" asp-area="" asp-controller="CitacaoEdital" asp-action="Index">
                  <i class="fas fa-copy"></i> Citação por Edital
                </a>
                <a class="dropdown-item" asp-area="" asp-controller="ConversaoExecucao" asp-action="Index">
                  <i class="fas fa-copy"></i> Conversao em Execucao
                </a>
                <a class="dropdown-item" asp-area="" asp-controller="ConversaoExecucaoItau" asp-action="Index">
                  <i class="fas fa-copy"></i> Conversao em Execucao - Itaú
                </a>
                <a class="dropdown-item" asp-area="" asp-controller="ExpedicaoNovoMandado" asp-action="Index">
                  <i class="fas fa-copy"></i> Expedicao de Mandado
                </a>
                <a class="dropdown-item" asp-area="" asp-controller="ExpedicaoMandadoCitacao" asp-action="Index">
                  <i class="fas fa-copy"></i> Expedicao de Mandado por Citação
                </a>
                <a class="dropdown-item" asp-area="" asp-controller="FielDepositario" asp-action="Index">
                  <i class="fas fa-copy"></i> Fiel Depositário
                </a>
                <a class="dropdown-item" asp-area="" asp-controller="InformarEndereco" asp-action="Index">
                  <i class="fas fa-copy"></i> Informar Endereço
                </a>
                <a class="dropdown-item" asp-area="" asp-controller="InformarOrgaos" asp-action="Index">
                  <i class="fas fa-copy"></i> Informar Órgãos para Expedição e Ofícios
                </a>
                <a class="dropdown-item" asp-area="" asp-controller="JuntadaTermoCessao" asp-action="Index">
                  <i class="fas fa-copy"></i> Juntada de Termo de Cessão
                </a>
              </div>
            </li>


            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle text-white hvr-underline-reveal" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-lock"></i> Administrativo
              </a>
              <div class="dropdown-menu dropdown-dark" aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item" asp-area="Identity" asp-page="/Account/Register">
                  <i class="fas fa-plus-circle"></i>&nbsp; Cadastro de Usuario
                </a>
                <a class="dropdown-item" asp-area="" asp-controller="Role" asp-action="Index">
                  <i class="fas fa-tools"></i>&nbsp; Regras de Usuarios
                </a>
              </div>
            </li>
          </ul>
          <partial name="_LoginPartial" />
        </div>
      </nav>
      <!--/.Navbar -->
    }
  </header>
  <div class="container-fluid">

    <main role="main" class="pb-3">
      @RenderBody()
    </main>
  </div>

  <!-- jQuery -->
  <script type="text/javascript" src="~/js/jquery.min.js"></script>
  <!-- Bootstrap tooltips -->
  <script type="text/javascript" src="~/js/popper.min.js"></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src="~/js/bootstrap.min.js"></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src="~/js/mdb.min.js"></script>
  <!-- Stepper JavaScript - minified -->
  <script type="text/javascript" src="~/js/addons-pro/steppers.min.js"></script>
  <!-- Mascaras  -->
  <script type="text/javascript" src="~/js/jquery.maskMoney.js"></script>
  <!-- Datas  -->
  <script type="text/javascript" src="~/js/moment.min.js"></script>
  <script type="text/javascript" src="~/js/pt-br.min.js"></script>
  <script type="text/javascript" src="~/js/jquery.maskedinput.js"></script>
  <script src="~/js/site.js" asp-append-version="true"></script>
  <script src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js"></script>
  <script src="https://cdn.datatables.net/1.10.24/js/dataTables.bootstrap4.min.js"></script>

  <script>
    $(document).ready(function () {
      $('#notificacao').mdbDropSearch();
    });
  </script>

  @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Layout2.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<!DOCTYPE html>
<html lang="pt-br">
<head>

  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="~/css/bootstrap.min.css">
  <!-- Material Design Bootstrap -->
  <link rel="stylesheet" href="~/css/mdb.min.css">

  <link rel="stylesheet" href="~/css/StyleSheet.css">

</head>
<body>
  <header>
  </header>

      @RenderBody()


  @await RenderSectionAsync("Scripts", required: false)
</body>
</html>